version: '3'

services:
  app:
    image: 'docker-tenpo-interview:latest'
    build:
      context: src/main/docker
    container_name: tenpo_interview_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo_interview
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tenpo_interview
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"