version: '3'

services:
  app:
    image: 'tenpo-interview:latest'
    build:
      context: src/main/docker
    container_name: tenpo_interview_app
    depends_on:
      - db
      - redis-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo_interview
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080
  redis-server:
    image: "redis:6.2.6"
    command: redis-server
    ports:
      - "6379:6379"
  db:
    image: 'postgres:14.1'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tenpo_interview