version: '4'

services:
  app:
    image: 'tenpo-interview:latest'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo_interview
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080
    links:
      - redis
  db:
    image: 'postgres:14.1'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tenpo_interview
  redis:
    container_name: redis
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"